cmake_minimum_required(VERSION 3.16)
project(rover_vision LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
find_package(stella_vslam REQUIRED)
find_package(OpenCV REQUIRED COMPONENTS core imgcodecs imgproc video)
add_executable(rover-vision worker.cc)
target_link_libraries(rover-vision PRIVATE stella_vslam::stella_vslam ${OpenCV_LIBS})
target_include_directories(rover-vision PRIVATE ${OpenCV_INCLUDE_DIRS})
